global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'binance-exporter'
    static_configs:
      - targets: 
        - 'binance-exporter:9890'
        - 'binance-exporter:9892'
        - 'binance-exporter:9894'
        - 'binance-exporter:9896'
        - 'binance-exporter:9898'
  - job_name: 'grafana'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']
