global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'binance-ohlc'
    scrape_interval: 15s 
    static_configs:
      # Use the Docker service name 'ohlc-exporter'
      - targets: ['ohlc-exporter:9001']
  - job_name: 'grafana'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']
