apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090  # Use the Docker service name 'prometheus'
    access: proxy
    isDefault: true
    orgId: 1
    uid: ff37xvoluc6wwb
    version: 1
    editable: false